plugins {
    id 'com.gradleup.shadow' version '9.2.2' apply false
}

allprojects {
    group = 'net.hasor'
}

subprojects {
    plugins.withType(JavaPlugin).configureEach {
        java {
            toolchain.languageVersion = JavaLanguageVersion.of(17)
        }
        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
            options.release = 17
        }
        tasks.withType(Javadoc).configureEach {
            options.encoding = 'UTF-8'
            options.addStringOption('Xdoclint:none', '-quiet')
            failOnError = false
        }
        tasks.withType(Test).configureEach {
            useJUnit()
            ignoreFailures = true
            jvmArgs '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
                    '--add-opens', 'java.base/java.lang.reflect=ALL-UNNAMED',
                    '--add-opens', 'java.base/java.io=ALL-UNNAMED',
                    '--add-opens', 'java.base/java.net=ALL-UNNAMED'
        }
        tasks.withType(GenerateModuleMetadata).configureEach { enabled = false }
        dependencies { testImplementation "junit:junit:${property('lib.junit')}" }
    }
}
