pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

rootProject.name = 'dataql-parent'

// dataql
include 'dataql-engine'
include 'dataql-sqlproc'
project(':dataql-engine').projectDir = file('dataql/dataql-engine')
project(':dataql-sqlproc').projectDir = file('dataql/dataql-sqlproc')

// dataway for embedded
include 'dataway-embedded'
include 'dataway-embedded-web'
project(':dataway-embedded').projectDir = file('dataway/embedded')
project(':dataway-embedded-web').projectDir = file('dataway/embedded-web')

// Optional framework adapters.
include 'dataway-hasor'
include 'dataway-solon'
include 'dataway-spring'
project(':dataway-hasor').projectDir = file('integration/dataway-hasor')
project(':dataway-solon').projectDir = file('integration/dataway-solon')
project(':dataway-spring').projectDir = file('integration/dataway-spring')

// Optional storage extensions.
include 'dataway-meta-jdbc'
include 'dataway-meta-nacos'
project(':dataway-meta-jdbc').projectDir = file('integration/dataway-meta-jdbc')
project(':dataway-meta-nacos').projectDir = file('integration/dataway-meta-nacos')
