/*
 * Copyright 2015-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':dataway-embedded')
    api platform('org.springframework.boot:spring-boot-dependencies:4.1.1')
    api 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2:2.5.250'
}
