<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.hasor</groupId>
        <artifactId>dataql-parent</artifactId>
        <version>4.3.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <!-- Maven Info -->
    <artifactId>hasor-dataql</artifactId>
    <packaging>jar</packaging>

    <!-- Project Info -->
    <name>DataQL Engine</name>
    <description>the hasor DataQL project.</description>

    <developers>
        <developer>
            <name>赵永春(Mr.Zhao)</name>
            <email>zyc@hasor.net</email>
        </developer>
    </developers>

    <build>
        <plugins>
            <!-- 把 antlr4 目录的 g4 文件生源代码到 target/generated-sources/antlr4 目录下 -->
            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-maven-plugin</artifactId>
                <version>4.9.1</version>
                <executions>
                    <execution>
                        <configuration>
                            <arguments>
                                <argument>-package</argument>
                                <argument>net.hasor.dataql.parser</argument>
                            </arguments>
                            <visitor>true</visitor>
                        </configuration>
                        <goals>
                            <goal>antlr4</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- 把生成的 DataQL tokens 文件放回 g4 目录（为了 IDE 插件） -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <configuration>
                            <target>
                                <copy file="${basedir}/target/generated-sources/antlr4/DataQLLexer.tokens"
                                      tofile="${basedir}/src/main/antlr4/DataQLLexer.tokens"/>
                                <copy file="${basedir}/target/generated-sources/antlr4/DataQLParser.tokens"
                                      tofile="${basedir}/src/main/antlr4/DataQLParser.tokens"/>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <!-- 引用依赖 -->
    <dependencies>
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4-runtime</artifactId>
            <version>4.9.1</version>
        </dependency>
        <dependency>
            <groupId>net.hasor</groupId>
            <artifactId>cobble-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
