/*
 * Copyright 2015-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
plugins {
    id 'java-library'
    id 'maven-publish'
}

ext.pomName = 'Dataway Metadata Nacos'
description = 'Nacos metadata storage extension for Dataway.'

dependencies {
    api project(':dataway-embedded')
    api 'com.alibaba.nacos:nacos-client:3.1.2'

    // for test
    testImplementation 'org.mockito:mockito-core:5.23.0'
}
