/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "DataQL - 数据查询语言",
  "tagline": "DataQL 数据查询语言",
  "url": "https://www.dataql.net",
  "baseUrl": "/en/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "zycgit",
  "projectName": "dataql",
  "i18n": {
    "defaultLocale": "zh-cn",
    "locales": [
      "zh-cn",
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/zyc/project/hasor/dataql/document/sidebars.js",
          "editUrl": "https://gitee.com/zycgit/dataql-doc/tree/master/"
        },
        "theme": {
          "customCss": "/home/zyc/project/hasor/dataql/document/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "keywords",
        "content": "sql,dataway,hasor,dataql,开源,开源软件,java开源,开源项目,开源代码"
      },
      {
        "name": "description",
        "content": "DataQL（Data Query Language）是一种查询语言。旨在通过提供直观、灵活的语法来描述客户端应用程序的数据需求和交互。"
      }
    ],
    "colorMode": {
      "disableSwitch": true,
      "defaultMode": "light",
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "logo": {
        "alt": "DataQL Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "dataql/overview",
          "position": "left",
          "label": "DataQL 语言"
        },
        {
          "type": "doc",
          "docId": "dataway/overview",
          "position": "left",
          "label": "Dataway 框架"
        },
        {
          "type": "doc",
          "docId": "integration/overview",
          "position": "left",
          "label": "框架整合"
        },
        {
          "type": "doc",
          "docId": "releases/latest",
          "position": "left",
          "label": "发布版本"
        },
        {
          "type": "dropdown",
          "label": "源代码",
          "position": "left",
          "items": [
            {
              "label": "Gitee",
              "href": "https://gitee.com/zycgit/dataql"
            },
            {
              "label": "Github",
              "href": "https://github.com/zycgit/dataql"
            }
          ]
        },
        {
          "position": "right",
          "label": "Hasor 框架",
          "href": "https://www.hasor.net/"
        },
        {
          "position": "right",
          "label": "dbVisitor ORM",
          "href": "https://www.dbvisitor.net/"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false,
      "title": "dbVisitor"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2022 dbVisitor. Built with Docusaurus.<br/>\n<a target=\"_blank\" href=\"http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33011002013536\">\n<img src=\"/img/beian.png\" style=\"display: inline-block;\">浙公网安备 33011002013536号\n</a>&nbsp;&nbsp;<a target=\"_blank\" href=\"http://www.beian.miit.gov.cn/\">浙ICP备18034797号</a>\n<div id=\"analyticsDiv\" style=\"display: inline-block;\"></div>",
      "links": []
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    null,
    [
      "/home/zyc/project/hasor/dataql/document/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js",
      {
        "indexPages": true,
        "language": [
          "en",
          "zh"
        ],
        "maxSearchResults": 8
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
