/*
 * Copyright 2015-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':dataway-embedded')
    api 'org.noear:solon:4.1.0'
    implementation 'org.noear:solon-handle:4.1.0'
    testImplementation 'org.noear:solon-test:4.1.0'
    testImplementation 'com.h2database:h2:2.5.250'
    testRuntimeOnly 'org.noear:solon-server-smarthttp:4.1.0'
}
