/*
 * Copyright 2015-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':dataway-embedded')
    api "net.hasor:hasor-web:${property('lib.hasor')}"
    api 'javax.servlet:javax.servlet-api:4.0.1'

    // optional
    compileOnly project(':dataway-meta-jdbc')
    compileOnly "net.hasor:dbvisitor:${property('lib.dbvisitor')}"

    // for test
    testImplementation project(path: ':dataql-sqlproc', configuration: 'shadow')
    testImplementation project(':dataway-meta-jdbc')
    testImplementation "net.hasor:dbvisitor-hasor:${property('lib.dbvisitor')}"
    testImplementation 'com.h2database:h2:2.5.250'
    testImplementation "net.hasor:hasor-boot-web-tomcat:${property('lib.hasor')}"
    testImplementation 'com.squareup.okhttp3:okhttp-jvm:5.3.2'
    testImplementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
}
