/*
 * Copyright 2015-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':dataway-embedded')
    api "net.hasor:hasor-web:${property('lib.hasor')}"
    api 'javax.servlet:javax.servlet-api:4.0.1'

    // for test
    testRuntimeOnly 'com.google.code.gson:gson:2.12.1'
    testImplementation project(':dataway-meta-jdbc')
    testImplementation 'com.h2database:h2:2.5.250'
    testImplementation project(':dataway-meta-nacos')
}
