plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

gradlePlugin {
    plugins {
        centralPublish {
            id = 'dataql.central-publish'
            implementationClass = 'net.hasor.dataql.gradle.DataqlCentralPublishPlugin'
        }
    }
}
