/*
 * Copyright 2015-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE.txt file for the full license.
 * https://www.apache.org/licenses/LICENSE-2.0
 */
plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':dataway-embedded')
    api "net.hasor:dbvisitor:${property('lib.dbvisitor')}"

    // for test
    testImplementation 'com.h2database:h2:2.5.250'
    testImplementation 'org.mockito:mockito-core:5.23.0'
}
